BROWSER = "Firefox"
BASE_URL = "https://www.mediamarkt.hu"
LOGIN_URL = "https://www.mediamarkt.hu/webapp/wcs/stores/servlet/LogonForm"
USERNAME = "avemee7777@gmail.com"
PASSWORD = "mosoly77"
REGISTERED_NAME = "Balázs"